import sys
import time
import json
from collections import defaultdict

sys.path.insert(0, '/opt/python')
from spotify import ensure_fresh_token, create_playlist, add_tracks_to_playlist
from db import (get_group, get_user, update_user, put_group,
                ok, err, get_user_id, log_event, GROUPS)


def lambda_handler(event, context):
    group_id = (event.get('pathParameters') or {}).get('groupId')
    if not group_id:
        return err('Missing groupId', 400)

    user_id = get_user_id(event)
    if not user_id:
        return err('Missing X-User-Id header', 401)

    body = {}
    if event.get('body'):
        try:
            body = json.loads(event['body'])
        except Exception:
            pass

    playlist_name = body.get('name', '')
    max_tracks = int(body.get('maxTracks', 30))

    group = get_group(group_id)
    if not group:
        return err('Group not found', 404)

    members = list(group.get('members') or set())
    if len(members) < 2:
        return err('Need at least 2 members to generate a playlist', 400)

    users = {}
    for uid in members:
        u = get_user(uid)
        if u:
            users[uid] = u

    requester = users.get(user_id)
    if not requester:
        return err('You are not a member of this group', 403)

    # Score every candidate track by how many members have it in their top 50
    track_score = defaultdict(lambda: {'score': 0, 'voters': [], 'uri': None, 'name': '', 'artist': ''})

    for uid, user in users.items():
        for tid in user.get('topTrackIds') or []:
            track_score[tid]['score'] += 1
            track_score[tid]['voters'].append(uid)

    # Rank by score descending, take top N
    ranked = sorted(track_score.items(), key=lambda x: -x[1]['score'])[:max_tracks]

    if not ranked:
        return err('No tracks found — members may need to refresh their profiles', 400)

    # Export to Spotify using the requester's account
    access, token_updates = ensure_fresh_token(requester)
    if token_updates:
        update_user(user_id, token_updates)

    group_name = group.get('name', 'Group')
    if not playlist_name:
        playlist_name = f"Harmonia: {group_name}"
    description = f"Generated by Harmonia for {len(members)} people. Group score powered by real Spotify data."

    t_start = time.time()
    export_success = False
    spotify_playlist_id = None
    spotify_playlist_url = None

    try:
        playlist = create_playlist(access, user_id, playlist_name, description)
        spotify_playlist_id  = playlist['id']
        spotify_playlist_url = playlist['external_urls']['spotify']

        track_uris = [f"spotify:track:{tid}" for tid, _ in ranked]
        add_tracks_to_playlist(access, spotify_playlist_id, track_uris)
        export_success = True
    except Exception as exc:
        log_event('playlist_export_error', group_id=group_id, error=str(exc))

    latency_ms = round((time.time() - t_start) * 1000, 1)

    # Persist playlist info on group record
    GROUPS().update_item(
        Key={'groupId': group_id},
        UpdateExpression='SET playlist = :p',
        ExpressionAttributeValues={':p': {
            'spotifyId':  spotify_playlist_id,
            'spotifyUrl': spotify_playlist_url,
            'name':       playlist_name,
            'trackCount': len(ranked),
            'createdAt':  int(time.time()),
        }},
    )

    log_event('playlist_generated',
              group_id=group_id,
              group_size=len(members),
              track_count=len(ranked),
              export_success=1 if export_success else 0,
              score_latency_ms=latency_ms)

    track_list = [
        {
            'trackId':  tid,
            'score':    meta['score'],
            'voterCount': len(meta['voters']),
        }
        for tid, meta in ranked
    ]

    return ok({
        'groupId':           group_id,
        'playlistName':      playlist_name,
        'spotifyPlaylistId': spotify_playlist_id,
        'spotifyUrl':        spotify_playlist_url,
        'trackCount':        len(ranked),
        'exportSuccess':     export_success,
        'tracks':            track_list,
    }, status=201)
